### ISSUE TITLE
Expected (8 bytes *sizeof(int64_t)) (512bit) descriptor but I only see 6 bytes (384 bits) set 

### ISSUE THREAD

**Issue by dgtlmoon** [komrad36/LATCH#3]
```
desc = new uint64_t[8 * keypoints.size()];

LATCH<multithread>(image.data, image.cols, image.rows, static_cast<int>(image.step), kps, desc);

int sixth = (desc[0] >> (6 * 8)) & 0xFF; // seems to always be zero
int seventh = (desc[0] >> (7 * 8)) & 0xFF; // seems to always be zero
```

`numkps = 5000` for the ORB detector and I've tried on image sizes from 8kb to 26Mb

**Comment by dgtlmoon** [comment]
Although, descriptor at desc[10] sometimes has that value set, unsure.. probably not an issue?

**Comment by komrad36** [comment]
Hi,

I am unable to reproduce. It can be hard to see what's going on with that kind of bit manipulation, so try something like this:

At the top of the file:
`#include <bitset>`

...then in main:
`for (int i = 0; i < 8; ++i) std::cout << std::bitset<64>(desc[i]) << std::endl;`

For the default test file from the git repo I obtain:
```
LATCH took 2.84164 us per desc over 4982 descs.

0110100001100101111111000001010100000110100001011001101101000101
0011000111110000001000100100001001100001100010100000000010100011
0001011001010010000001101100010111111010101101000101010001101000
0000100000110101100011001100100110000001110001101101110001010111
0010100001000101100001010101110001010000011011001101100010001000
1100100100010100000011000010010011010010100110100000101000100010
1110110011101100001111010111000000000101000101111010110000010010
1100000010010101111000010110110001011110011000101001000111000001

Checksum: e20544d8494d957f
```

That's a reasonable-looking LATCH descriptor! Let me know if yours looks different applied to the latest git commit. If it doesn't, it's likely to do with a modification you've made in the fork.

Thanks,
Kareem

**Comment by dgtlmoon** [comment]
Hey that `bitset` library is great! thanks

OK So... yeah quite different, using https://raw.githubusercontent.com/komrad36/LATCH/master/test.jpg

keypoints is 5000.. 5000 are found.

```
0000000000000000011111110101101110010111101110111111101101111000
0000000000000000000000000000000000000000011011111101011110100000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
1011111110000000000000000000000001000010000101001100110011001101
0000000000000000000000000000000101000010110110100000000000000000
0100001110011111000000000000000011111111111111111111111111111111
0100001000010100110011001100110101000010110110000000000000000000
```

Here's my flow..

```
            cv::Mat image = cv::imread(entry.path().string(), CV_LOAD_IMAGE_GRAYSCALE);
            cv::Ptr<cv::ORB> orb = cv::ORB::create(numkps, 1.2f, 8, 31, 0, 2, cv::ORB::HARRIS_SCORE, 31, 20);
            orb->detect(image, keypoints);
            descriptor = new uint64_t[8 * keypoints.size()];
            LATCH<multithread>(image.data, image.cols, image.rows, static_cast<int>(image.step), kps, descriptor);
                for (int i = 0; i < 8; ++i) std::cout << std::bitset<64>(descriptor[i]) << std::endl;
```

**Comment by dgtlmoon** [comment]
Forgot to add, OpenCV 3.1 on Ubuntu here

**Comment by dgtlmoon** [comment]
Ok looks like it's my own issue somehow - this repo's LATCH code outputs the same bits as you pasted above, compiled against the same OpenCV I'm running.. so hmm...

**Comment by dgtlmoon** [comment]
However it's not exactly the same....


```
Detecting...
Warming up...
Testing...
1101110011000110011100000100110010010011001000010110000100110110
0001101010101100100011000001001010100100111110000010000111011100
1010000100011110110110011110100101000110111000010101001111101001
0101010011100001001011001000000101100001000000011001000001000011
0101010101011111000010100010011101110011100001011101100011101010
0111000010100110010011011000100000101101001010001100110100001101
1111000001011110101000100000011111000010011000000001000001100111
0110011100111010100010101000110110001111010101111010010001111100

LATCH took 3.22416 us per desc over 4981 descs.

Checksum: 177d09fd3e3307bb

```

debug is after the LATCH<multithread>
```
        for (int i = 0; i < runs; ++i) LATCH<multithread>(image.data, image.cols, image.rows, static_cast<int>(image.step), kps, desc);
+       for (int i = 0; i < 8; ++i) std::cout << std::bitset<64>(desc[i]) << std::endl;

```

**Comment by komrad36** [comment]
One of a GIANT laundry list of things wrong with OpenCV is that it differs
by platform. Mine was run on Windows, and it's known that the ORB detector
returns different output across the two operating systems. So no worries
there. I promise LATCH works the same on both. You can see why I'm working
on completely replacing the pipeline :-)

Thanks,
Kareem

**Comment by dgtlmoon** [comment]
I was missing your conversion from degrees to radians ;) yes! i look forwards to an update, thanks again!

**Comment by dgtlmoon** [comment]
I still can't believe how insanely fast even the "slow" CPU implementation of this is.. wow!

**Comment by komrad36** [comment]
:)

**Comment by dgtlmoon** [comment]
unrelated, but maybe interesting here is CPU support for popcount's..

https://en.wikipedia.org/wiki/SSE4#POPCNT_and_LZCNT

**Comment by komrad36** [comment]
So that's actually what I use in K2NN:

```
_mm_popcnt_u64(qa ^ t64[tp])
...
```

Resulting assembly:
```
 mov         rax,qword ptr [r9+8]  
 xor           rax,rcx  
 popcnt     r8,rax
...
```

So depending how much you want to know about this stuff... popcounts are a major focus for anyone doing binary descriptor work. I have experimented with dozens of different approaches to find the fastest way. Here is a brief overview of the history of popcount (free of charge! :D):

In the early days popcount was actually easy. The IBM stretch computer, produced in 1960, had population count. No, to state it had population count would be an understatement. It produced both the population count AND the leading zero count AS A BYPRODUCT of all logical operations!
And then it was 52 years before we had that capability again in mainstream architecture. This is very puzzling to people like me who play on the bare metal and really need this operation, and wonder what they were thinking.

Anyway so after we lost that capability, focus turned to bitbashing methods for computing it. Table lookup methods used to win, because memory was faster than compute. As time went on and compute became faster than memory, and more parallel, this became less true and it became cheaper to compute more. However, the fastest bitbashing methods are still pathetic, taking **dozens** of cycles for a 64-bit popcount.

Work therefore focused on ways to actually avoid having to do so many popcounts, which seems impossible but isn't. Harley and Seal developed a carry-save add (CSA) approach in which you vertically add two 64-bit values before popcounting them. Obviously, when you do this...

```
0011
+
1010
=
1021
```

...you have the possibility of overflowing some bits, so you'd have to store each bit's answer in _two_ bits, and then you have two new uint64s from the two you started with and are thus no better off - in fact, you're worse because you just wasted a bunch of cycles doing a CSA.

HOWEVER, the clever thing Harley and Seal did is to realize that you only need _three_ possible values to store such a CSA output bit: 0, 1, and 2. Therefore if you went to two full bits, which is four possible values, you'd be wasting a bit. Therefore why not add **three** vectors together via CSA:

```
0011
+
1010
+
1011
=
2032
```

Now you can use two answer bits to store each one. Split it into two uint64s, the "high" and "low":

```
H: 1011
L:  0010
```

Where you reconstruct the answer by doing twice the high plus the low:

`answer = 2*(1011) + 0010 = 2022 + 0010 = 2032`

Okay, now notice something awesome: **if you popcount H, shift that answer left by 1 (i.e. double it), then popcount L and add up, you've computed the popcount of 3 input vectors but only done 2 expensive popcounts - a 50% strength reduction!!** (It is 50%, not 33%, promise: in the time needed to do 6 popcounts, you used to get 2 units of work, now you get 3 units of work done: a 50% increase.)

Note that the actual gain is less than 50% because of the work you have to do to prepare a CSA. However, Seal later noticed that you can actually do this recursively a few times, say 8 or 16, depending on how many 64-bit registers you have sitting around. This decreases the order of the wasted work and brings the speedup closer to 50%.

Note that you have to be wanting to popcount a fairly large value, like 512 bits or more, for this to make sense, since Harley-Seal computes combined popcount of many 64-bit values.

So for a long time, a very sophisticated recursive application of Harley-Seal was the fastest way to popcount.

Then SSE4 and AVX2 come along, and now there are two new ways to compute popcount: apply Harley-Seal to 256-bit YMM registers (delicious), or just apply the new popcnt instruction to 64-bit regs while streaming in data (also very tasty).

Getting Harley-Seal to work in AVX2 was extremely difficult. You repeatedly don't have the instruction you need but are able, barely, after an hour at a whiteboard, to prove that another instruction that isn't quite right will still produce the correct result because of where you are in the Harley-Seal process. I got it working eventually, for variable power-of-two vector sizes.

Getting POPCNT to work is easy in comparison, except it isn't, because Intel. **Since Intel's introduction of POPCNT in Nehalem, there has been a false data dependency on the destination register.** This is a hardware bug in all Intel processors that they seem to be in no hurry to fix, since I still see it in Skylake.

This means that a naive application of POPCNT will die in a fire, with its throughput dropping by 67% (three logical units).

This bug can be worked around easily in assembly. Recent gcc and clang do a pretty good job of idiom recognition and work around it for you from C++.

MSVC still conditionally dies in a fire depending, basically, on how many free registers you have around you, which determines how aggressively it optimizes (ruins) your attempt to break the dependency. **Consequently when writing code involving POPCNT in MSVC, seemingly unrelated actions like changing the size of a loop counter variable can affect the speed of your code by a factor of 3**, which is the sort of thing that makes profile-guided optimization, and human programmers for that matter, if unaware of the bug, cry a Niagara of tears.

![the more you know](https://cloud.githubusercontent.com/assets/13008770/21197043/f9d1c1a2-c207-11e6-8a54-16d5aa2908bb.gif)

If you break the false dependency, the POPCNT instruction is 1 cycle, 1 latency on AMD Jag and 1 cycle, 1 latency on Intel Nehalem and up, even for 64-bit (!).

So what's the fastest on modern architectures? Well, POPCNT being only 1 cycle if you work around the bug is really fast. You **cannot** commpete with that for popcounting 64 bits of data, or 128, or 256...

However, if you are popcounting a very large vector, **AVX2 Harley-Seal still wins!** The vector has to be somewhere between 1024 and 4096 bytes for this to be the case, depending on arch and memory speed.

Bottom line: use POPCNT (but make sure you break the false dependency! Use assembly or inspect your compiler output!) for vectors <= 512. Use AVX2 Harley-Seal for vectors >= 4096. In between sizes, try both and profile to see what wins.

But then CUDA was like "look I can hardware popcount trololo" and then it was just completely game over. We're talking up to ~50 GB/s of popcounts using Harley-Seal or POPCNT on a Skylake. We're talking up to ~2 TB/s using CUDA on a GTX 1080. It is _ridiculous_. But not if you do it naively! You'll bottleneck the memory controller, and if you're doing n^2 like we are and you try to optimize by holding on to a whole query vector and then bringing in 1 training vector at a time, that's 16 64-bit values, which is 32 32-bit registers, which means you'll die in a fire under the register pressure. Hence CUDAK2NN uses a novel multi-reduction strategy which was my friend @csp256's idea, allowing just 18 32-bit registers to be used but to get equivalent alleviation of required memory bandwidth.

Okay, so bottom bottom line. Have a recent GPU and willing to spend lots of time writing insane CUDA kernels? Use CUDA, it's awesome at popcounting. No GPU and old CPU? Get a new CPU or use scalar Harley-Seal. New CPU? Use POPCNT (but make sure you break the false dependency) for vectors <= 512. Use AVX2 Harley-Seal for vectors >= 4096. In between sizes, try both and profile to see what wins.

Alright, that's more than you ever wanted to know about population counts, I'm sure, but I think it's a complete survey of historical and modern approaches. :D

**Comment by komrad36** [comment]
Hi,

Just wanted to mention that after lots of difficulties and delays my detector-descriptor is finally ready, or at least, ready enough to make public! I still have a lot of work and tweaking to do on it, but it's at least available so you can get an idea and hopefully benefit from the increased accuracy and speed that comes from the way it shares scale spaces, for superior rotation- and scale-invariance without any loss of performance. It's called KORAL and is available here: https://github.com/komrad36/KORAL.

Thanks!
-Kareem

**Comment by dgtlmoon** [comment]
@komrad36 incredible work! compiles and runs cleanly here (Ubuntu/GeForce GTX 960M/Cuda 8)

**Comment by dgtlmoon** [comment]
@komrad36 quick question - so basically, where to from here with regards to ensuring the matched keypoints/descriptors are in the same physical area of the image across the two images/frames/etc of descriptors? is there some way of dealing with that?
